create table if not exists projects(
    id integer primary key generated by default as identity,
    name text not null check (name <> ''),
    priority integer not null,
    description text,
    deliverydate date not null
);

create table if not exists tasks(
    id integer primary key generated by default as identity,
    name text not null check (name <> ''),
    done boolean,
    projectId integer REFERENCES projects(id)
);

-- Insert Project data
insert into projects(name, priority, description, deliverydate) 
    values('Make a web app', 1,'using JavaScript', '2019-05-12');

insert into projects(name, priority, description, deliverydate) 
    values('Make an app', 1,'using dart', '2019-05-13');

insert into projects(name, priority, description, deliverydate) 
    values('Make a dektop app', 1,'using c++', '2019-05-14');

--Insert task DATA
insert into tasks(name, done, projectId) 
    values('Download Vue.js', false ,1);

insert into tasks(name, done, projectId) 
    values('Download Android Studio', true ,1);

insert into tasks(name, done, projectId) 
    values('Create UI web', false ,2);